### ISSUE TITLE
docker 构建失败

### ISSUE THREAD

**Issue by 631068264** [pkeropen/hadoop-docker-lite#1]
```
(.env) ➜  hadoop-docker-lite-master docker-compose ps
                  Name                                 Command                State                                            Ports                                        
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
hadoop-docker-lite-master_hadoop_1          /etc/bootstrap.sh -d             Up         22/tcp, 0.0.0.0:49707->49707/tcp, 0.0.0.0:50010->50010/tcp,                         
                                                                                        0.0.0.0:50020->50020/tcp, 0.0.0.0:50030->50030/tcp, 0.0.0.0:50070->50070/tcp,       
                                                                                        0.0.0.0:50075->50075/tcp, 0.0.0.0:50090->50090/tcp, 0.0.0.0:8030->8030/tcp,         
                                                                                        0.0.0.0:8031->8031/tcp, 0.0.0.0:8032->8032/tcp, 0.0.0.0:8033->8033/tcp,             
                                                                                        0.0.0.0:8040->8040/tcp, 0.0.0.0:8042->8042/tcp, 0.0.0.0:8088->8088/tcp              
hadoop-docker-lite-master_hbase_1           /bin/sh -c start-hbase.sh        Exit 0                                                                                         
hadoop-docker-lite-master_kafka-manager_1   ./start-kafka-manager.sh         Up         0.0.0.0:9000->9000/tcp                                                              
hadoop-docker-lite-master_kafka_1           /bin/sh -c /usr/bin/start- ...   Exit 137                                                                                       
hadoop-docker-lite-master_nimbus_1          /bin/sh -c /usr/bin/start- ...   Up         0.0.0.0:32772->22/tcp, 0.0.0.0:49772->3772/tcp, 0.0.0.0:49773->3773/tcp,            
                                                                                        0.0.0.0:49627->6627/tcp                                                             
hadoop-docker-lite-master_supervisor_1      /bin/sh -c /usr/bin/start- ...   Up         0.0.0.0:32775->22/tcp, 6700/tcp, 6701/tcp, 6702/tcp, 6703/tcp,                      
                                                                                        0.0.0.0:32774->8000/tcp                                                             
hadoop-docker-lite-master_ui_1              /bin/sh -c /usr/bin/start- ...   Up         0.0.0.0:32773->22/tcp, 0.0.0.0:49080->8080/tcp                                      
hadoop-docker-lite-master_zookeeper_1       /opt/zookeeper/bin/zkServe ...   Up         0.0.0.0:2181->2181/tcp, 2888/tcp, 3888/tcp    
```

hbase
```
hbase_1          | 2019-11-03 09:47:25,233 INFO  [main] zookeeper.ZooKeeper: Client environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
hbase_1          | 2019-11-03 09:47:25,233 INFO  [main] zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
hbase_1          | 2019-11-03 09:47:25,233 INFO  [main] zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
hbase_1          | 2019-11-03 09:47:25,233 INFO  [main] zookeeper.ZooKeeper: Client environment:os.name=Linux
hbase_1          | 2019-11-03 09:47:25,233 INFO  [main] zookeeper.ZooKeeper: Client environment:os.arch=amd64
hbase_1          | 2019-11-03 09:47:25,233 INFO  [main] zookeeper.ZooKeeper: Client environment:os.version=4.9.184-linuxkit
hbase_1          | 2019-11-03 09:47:25,234 INFO  [main] zookeeper.ZooKeeper: Client environment:user.name=root
hbase_1          | 2019-11-03 09:47:25,234 INFO  [main] zookeeper.ZooKeeper: Client environment:user.home=/root
hbase_1          | 2019-11-03 09:47:25,234 INFO  [main] zookeeper.ZooKeeper: Client environment:user.dir=/opt/hbase-1.1.2/bin
hbase_1          | 2019-11-03 09:47:25,235 INFO  [main] zookeeper.ZooKeeper: Initiating client connection, connectString=zk:2181 sessionTimeout=90000 watcher=master:600000x0, quorum=zk:2181, baseZNode=/hbase
hbase_1          | 2019-11-03 09:47:25,337 INFO  [main-SendThread(zk:2181)] zookeeper.ClientCnxn: Opening socket connection to server zk/10.17.0.2:2181. Will not attempt to authenticate using SASL (unknown error)
hbase_1          | 2019-11-03 09:47:25,398 INFO  [main-SendThread(zk:2181)] zookeeper.ClientCnxn: Socket connection established to zk/10.17.0.2:2181, initiating session
hbase_1          | 2019-11-03 09:47:25,508 INFO  [main-SendThread(zk:2181)] zookeeper.ClientCnxn: Session establishment complete on server zk/10.17.0.2:2181, sessionid = 0x16e30a93bf00003, negotiated timeout = 40000
hbase_1          | 2019-11-03 09:47:25,879 INFO  [RpcServer.responder] ipc.RpcServer: RpcServer.responder: starting
hbase_1          | 2019-11-03 09:47:25,892 INFO  [RpcServer.listener,port=60000] ipc.RpcServer: RpcServer.listener,port=60000: starting
hbase_1          | 2019-11-03 09:47:26,416 INFO  [main] mortbay.log: Logging to org.slf4j.impl.Log4jLoggerAdapter(org.mortbay.log) via org.mortbay.log.Slf4jLog
hbase_1          | 2019-11-03 09:47:26,430 INFO  [main] http.HttpRequestLog: Http request log for http.requests.master is not defined
hbase_1          | 2019-11-03 09:47:26,489 INFO  [main] http.HttpServer: Added global filter 'safety' (class=org.apache.hadoop.hbase.http.HttpServer$QuotingInputFilter)
hbase_1          | 2019-11-03 09:47:26,504 INFO  [main] http.HttpServer: Added filter static_user_filter (class=org.apache.hadoop.hbase.http.lib.StaticUserWebFilter$StaticUserFilter) to context master
hbase_1          | 2019-11-03 09:47:26,511 INFO  [main] http.HttpServer: Added filter static_user_filter (class=org.apache.hadoop.hbase.http.lib.StaticUserWebFilter$StaticUserFilter) to context static
hbase_1          | 2019-11-03 09:47:26,511 INFO  [main] http.HttpServer: Added filter static_user_filter (class=org.apache.hadoop.hbase.http.lib.StaticUserWebFilter$StaticUserFilter) to context logs
hbase_1          | 2019-11-03 09:47:26,564 INFO  [main] http.HttpServer: Jetty bound to port 60010
hbase_1          | 2019-11-03 09:47:26,564 INFO  [main] mortbay.log: jetty-6.1.26
hbase_1          | 2019-11-03 09:47:29,833 INFO  [main] mortbay.log: Started SelectChannelConnector@0.0.0.0:60010
hbase_1          | 2019-11-03 09:47:29,897 INFO  [main] master.HMaster: hbase.rootdir=hdfs://10.17.0.3:9000/hbase, hbase.cluster.distributed=true
hbase_1          | 2019-11-03 09:47:30,128 INFO  [main] master.HMaster: Adding backup master ZNode /hbase/backup-masters/hbase,60000,1572774439746
hbase_1          | 2019-11-03 09:47:30,929 INFO  [hbase:60000.activeMasterManager] master.ActiveMasterManager: Current master has this master's address, hbase,60000,1572773246180; master was restarted? Deleting node.
hbase_1          | 2019-11-03 09:47:31,041 INFO  [hbase:60000.activeMasterManager] master.ActiveMasterManager: Deleting ZNode for /hbase/backup-masters/hbase,60000,1572774439746 from backup master directory
hbase_1          | 2019-11-03 09:47:31,058 WARN  [hbase:60000.activeMasterManager] hbase.ZNodeClearer: Environment variable HBASE_ZNODE_FILE not set; znodes will not be cleared on crash by start scripts (Longer MTTR!)
hbase_1          | 2019-11-03 09:47:31,058 INFO  [hbase:60000.activeMasterManager] master.ActiveMasterManager: Registered Active Master=hbase,60000,1572774439746
hbase_1          | 2019-11-03 09:47:31,645 INFO  [master/hbase/10.17.0.5:60000] zookeeper.RecoverableZooKeeper: Process identifier=hconnection-0x6097cabc connecting to ZooKeeper ensemble=zk:2181
hbase_1          | 2019-11-03 09:47:31,653 INFO  [master/hbase/10.17.0.5:60000] zookeeper.ZooKeeper: Initiating client connection, connectString=zk:2181 sessionTimeout=90000 watcher=hconnection-0x6097cabc0x0, quorum=zk:2181, baseZNode=/hbase
hbase_1          | 2019-11-03 09:47:31,698 INFO  [master/hbase/10.17.0.5:60000-SendThread(zk:2181)] zookeeper.ClientCnxn: Opening socket connection to server zk/10.17.0.2:2181. Will not attempt to authenticate using SASL (unknown error)
hbase_1          | 2019-11-03 09:47:31,765 INFO  [master/hbase/10.17.0.5:60000-SendThread(zk:2181)] zookeeper.ClientCnxn: Socket connection established to zk/10.17.0.2:2181, initiating session
hbase_1          | 2019-11-03 09:47:31,899 INFO  [master/hbase/10.17.0.5:60000-SendThread(zk:2181)] zookeeper.ClientCnxn: Session establishment complete on server zk/10.17.0.2:2181, sessionid = 0x16e30a93bf00005, negotiated timeout = 40000
hbase_1          | 2019-11-03 09:47:32,453 INFO  [master/hbase/10.17.0.5:60000] regionserver.HRegionServer: ClusterId : e492d6b1-e173-4b2a-aab8-08f25c2d1653
hbase_1          | 2019-11-03 09:47:33,794 INFO  [hbase:60000.activeMasterManager] util.FSUtils: Waiting for dfs to exit safe mode...
hbase_1          | 2019-11-03 09:47:43,816 INFO  [hbase:60000.activeMasterManager] util.FSUtils: Waiting for dfs to exit safe mode...
hbase_1          | 2019-11-03 09:47:55,272 INFO  [hbase:60000.activeMasterManager] util.FSUtils: Waiting for dfs to exit safe mode...
hbase_1          | 2019-11-03 09:48:10,212 INFO  [hbase:60000.activeMasterManager] util.FSUtils: Waiting for dfs to exit safe mode...
hbase_1          | 2019-11-03 09:50:18,916 WARN  [master/hbase/10.17.0.5:60000] util.Sleeper: We slept 28506ms instead of 3000ms, this is likely due to a long garbage collecting pause and it's usually bad, see http://hbase.apache.org/book.html#trouble.rs.runtime.zkexpired
hbase_1          | 2019-11-03 09:50:18,928 INFO  [main-SendThread(zk:2181)] zookeeper.ClientCnxn: Client session timed out, have not heard from server in 34745ms for sessionid 0x16e30a93bf00003, closing socket connection and attempting reconnect
hbase_1          | 2019-11-03 09:50:22,154 INFO  [master/hbase/10.17.0.5:60000-SendThread(zk:2181)] zookeeper.ClientCnxn: Client session timed out, have not heard from server in 37313ms for sessionid 0x16e30a93bf00005, closing socket connection and attempting reconnect
hbase_1          | 2019-11-03 09:50:27,643 INFO  [main-SendThread(zk:2181)] zookeeper.ClientCnxn: Opening socket connection to server zk/10.17.0.2:2181. Will not attempt to authenticate using SASL (unknown error)
hbase_1          | 2019-11-03 09:50:27,744 INFO  [master/hbase/10.17.0.5:60000-SendThread(zk:2181)] zookeeper.ClientCnxn: Opening socket connection to server zk/10.17.0.2:2181. Will not attempt to authenticate using SASL (unknown error)
hbase_1          | 2019-11-03 09:50:29,688 INFO  [master/hbase/10.17.0.5:60000-SendThread(zk:2181)] zookeeper.ClientCnxn: Socket connection established to zk/10.17.0.2:2181, initiating session
hbase_1          | 2019-11-03 09:50:29,923 INFO  [main-SendThread(zk:2181)] zookeeper.ClientCnxn: Socket connection established to zk/10.17.0.2:2181, initiating session
hbase_1          | 2019-11-03 09:50:43,621 INFO  [master/hbase/10.17.0.5:60000-SendThread(zk:2181)] zookeeper.ClientCnxn: Unable to reconnect to ZooKeeper service, session 0x16e30a93bf00005 has expired, closing socket connection
hbase_1          | 2019-11-03 09:50:45,468 INFO  [main-SendThread(zk:2181)] zookeeper.ClientCnxn: Unable to reconnect to ZooKeeper service, session 0x16e30a93bf00003 has expired, closing socket connection
hbase_1          | 2019-11-03 09:50:58,201 WARN  [master/hbase/10.17.0.5:60000-EventThread] client.ConnectionManager$HConnectionImplementation: This client just lost it's session with ZooKeeper, closing it. It will be recreated next time someone needs it
hbase_1          | org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired
hbase_1          |      at org.apache.hadoop.hbase.zookeeper.ZooKeeperWatcher.connectionEvent(ZooKeeperWatcher.java:606)
hbase_1          |      at org.apache.hadoop.hbase.zookeeper.ZooKeeperWatcher.process(ZooKeeperWatcher.java:517)
hbase_1          |      at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:522)
hbase_1          |      at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:498)
hbase_1          | 2019-11-03 09:51:48,549 INFO  [master/hbase/10.17.0.5:60000-EventThread] client.ConnectionManager$HConnectionImplementation: Closing zookeeper sessionid=0x16e30a93bf00005
hbase_1          | 2019-11-03 09:51:00,975 FATAL [main-EventThread] master.HMaster: master:60000-0x16e30a93bf00003, quorum=zk:2181, baseZNode=/hbase master:60000-0x16e30a93bf00003 received expired from ZooKeeper, aborting
hbase_1          | org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired
hbase_1          |      at org.apache.hadoop.hbase.zookeeper.ZooKeeperWatcher.connectionEvent(ZooKeeperWatcher.java:606)
hbase_1          |      at org.apache.hadoop.hbase.zookeeper.ZooKeeperWatcher.process(ZooKeeperWatcher.java:517)
hbase_1          |      at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:522)
hbase_1          |      at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:498)
hbase_1          | 2019-11-03 09:51:51,377 INFO  [master/hbase/10.17.0.5:60000-EventThread] zookeeper.ClientCnxn: EventThread shut down
hbase_1          | 2019-11-03 09:51:57,522 INFO  [main-EventThread] regionserver.HRegionServer: STOPPED: master:60000-0x16e30a93bf00003, quorum=zk:2181, baseZNode=/hbase master:60000-0x16e30a93bf00003 received expired from ZooKeeper, aborting
hbase_1          | 2019-11-03 09:52:00,198 INFO  [main-EventThread] zookeeper.ClientCnxn: EventThread shut down
hbase_1          | 2019-11-03 09:52:00,617 INFO  [master/hbase/10.17.0.5:60000] regionserver.HRegionServer: Stopping infoServer
hbase_1          | 2019-11-03 09:52:51,697 INFO  [JvmPauseMonitor] util.JvmPauseMonitor: Detected pause in JVM or host machine (eg GC): pause of approximately 1052ms
hbase_1          | No GCs detected
hbase_1          | 2019-11-03 09:52:55,873 INFO  [master/hbase/10.17.0.5:60000] mortbay.log: Stopped SelectChannelConnector@0.0.0.0:60010
hbase_1          | 2019-11-03 09:53:16,097 INFO  [JvmPauseMonitor] util.JvmPauseMonitor: Detected pause in JVM or host machine (eg GC): pause of approximately 9869ms
hbase_1          | No GCs detected
hbase_1          | 2019-11-03 09:53:30,175 INFO  [JvmPauseMonitor] util.JvmPauseMonitor: Detected pause in JVM or host machine (eg GC): pause of approximately 6580ms
hbase_1          | No GCs detected
hbase_1          | 2019-11-03 09:53:36,019 INFO  [JvmPauseMonitor] util.JvmPauseMonitor: Detected pause in JVM or host machine (eg GC): pause of approximately 1538ms
hbase_1          | No GCs detected
hbase_1          | 2019-11-03 09:53:41,439 INFO  [master/hbase/10.17.0.5:60000] regionserver.HRegionServer: stopping server hbase,60000,1572774439746
hbase_1          | 2019-11-03 09:53:44,307 INFO  [master/hbase/10.17.0.5:60000] regionserver.HRegionServer: stopping server hbase,60000,1572774439746; all regions closed.
hbase_1          | 2019-11-03 09:53:44,391 INFO  [master/hbase/10.17.0.5:60000] hbase.ChoreService: Chore service for: hbase,60000,1572774439746 had [] on shutdown
hbase_1          | 2019-11-03 09:53:44,392 WARN  [master/hbase/10.17.0.5:60000] zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=zk:2181, exception=org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /hbase/master
hbase_1          | 2019-11-03 09:53:46,645 WARN  [master/hbase/10.17.0.5:60000] zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=zk:2181, exception=org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /hbase/master
hbase_1          | 2019-11-03 09:53:49,165 WARN  [master/hbase/10.17.0.5:60000] zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=zk:2181, exception=org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /hbase/master
hbase_1          | 2019-11-03 09:53:53,201 WARN  [master/hbase/10.17.0.5:60000] zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=zk:2181, exception=org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /hbase/master
hbase_1          | 2019-11-03 09:54:01,274 WARN  [master/hbase/10.17.0.5:60000] zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=zk:2181, exception=org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /hbase/master
hbase_1          | 2019-11-03 09:54:01,301 ERROR [master/hbase/10.17.0.5:60000] zookeeper.RecoverableZooKeeper: ZooKeeper getData failed after 4 attempts
hbase_1          | 2019-11-03 09:54:01,302 WARN  [master/hbase/10.17.0.5:60000] zookeeper.ZKUtil: master:60000-0x16e30a93bf00003, quorum=zk:2181, baseZNode=/hbase Unable to get data of znode /hbase/master
hbase_1          | org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /hbase/master
hbase_1          |      at org.apache.zookeeper.KeeperException.create(KeeperException.java:127)
hbase_1          |      at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
hbase_1          |      at org.apache.zookeeper.ZooKeeper.getData(ZooKeeper.java:1155)
hbase_1          |      at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.getData(RecoverableZooKeeper.java:359)
hbase_1          |      at org.apache.hadoop.hbase.zookeeper.ZKUtil.getData(ZKUtil.java:745)
hbase_1          |      at org.apache.hadoop.hbase.zookeeper.MasterAddressTracker.getMasterAddress(MasterAddressTracker.java:148)
hbase_1          |      at org.apache.hadoop.hbase.master.ActiveMasterManager.stop(ActiveMasterManager.java:267)
hbase_1          |      at org.apache.hadoop.hbase.master.HMaster.stopServiceThreads(HMaster.java:1145)
hbase_1          |      at org.apache.hadoop.hbase.regionserver.HRegionServer.run(HRegionServer.java:1071)
hbase_1          |      at java.lang.Thread.run(Thread.java:748)
hbase_1          | 2019-11-03 09:54:01,580 ERROR [master/hbase/10.17.0.5:60000] zookeeper.ZooKeeperWatcher: master:60000-0x16e30a93bf00003, quorum=zk:2181, baseZNode=/hbase Received unexpected KeeperException, re-throwing exception
hbase_1          | org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /hbase/master
hbase_1          |      at org.apache.zookeeper.KeeperException.create(KeeperException.java:127)
hbase_1          |      at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
hbase_1          |      at org.apache.zookeeper.ZooKeeper.getData(ZooKeeper.java:1155)
hbase_1          |      at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.getData(RecoverableZooKeeper.java:359)
hbase_1          |      at org.apache.hadoop.hbase.zookeeper.ZKUtil.getData(ZKUtil.java:745)
hbase_1          |      at org.apache.hadoop.hbase.zookeeper.MasterAddressTracker.getMasterAddress(MasterAddressTracker.java:148)
hbase_1          |      at org.apache.hadoop.hbase.master.ActiveMasterManager.stop(ActiveMasterManager.java:267)
hbase_1          |      at org.apache.hadoop.hbase.master.HMaster.stopServiceThreads(HMaster.java:1145)
hbase_1          |      at org.apache.hadoop.hbase.regionserver.HRegionServer.run(HRegionServer.java:1071)
hbase_1          |      at java.lang.Thread.run(Thread.java:748)
hbase_1          | 2019-11-03 09:54:02,129 ERROR [master/hbase/10.17.0.5:60000] master.ActiveMasterManager: master:60000-0x16e30a93bf00003, quorum=zk:2181, baseZNode=/hbase Error deleting our own master address node
hbase_1          | org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /hbase/master
hbase_1          |      at org.apache.zookeeper.KeeperException.create(KeeperException.java:127)
hbase_1          |      at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
hbase_1          |      at org.apache.zookeeper.ZooKeeper.getData(ZooKeeper.java:1155)
hbase_1          |      at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.getData(RecoverableZooKeeper.java:359)
hbase_1          |      at org.apache.hadoop.hbase.zookeeper.ZKUtil.getData(ZKUtil.java:745)
hbase_1          |      at org.apache.hadoop.hbase.zookeeper.MasterAddressTracker.getMasterAddress(MasterAddressTracker.java:148)
hbase_1          |      at org.apache.hadoop.hbase.master.ActiveMasterManager.stop(ActiveMasterManager.java:267)
hbase_1          |      at org.apache.hadoop.hbase.master.HMaster.stopServiceThreads(HMaster.java:1145)
hbase_1          |      at org.apache.hadoop.hbase.regionserver.HRegionServer.run(HRegionServer.java:1071)
hbase_1          |      at java.lang.Thread.run(Thread.java:748)
hbase_1          | 2019-11-03 09:54:08,084 INFO  [master/hbase/10.17.0.5:60000] ipc.RpcServer: Stopping server on 60000
hbase_1          | 2019-11-03 09:54:11,043 INFO  [RpcServer.listener,port=60000] ipc.RpcServer: RpcServer.listener,port=60000: stopping
hbase_1          | 2019-11-03 09:54:13,443 INFO  [RpcServer.responder] ipc.RpcServer: RpcServer.responder: stopped
hbase_1          | 2019-11-03 09:54:13,841 INFO  [RpcServer.responder] ipc.RpcServer: RpcServer.responder: stopping
hbase_1          | 2019-11-03 09:54:16,924 WARN  [master/hbase/10.17.0.5:60000] zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=zk:2181, exception=org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /hbase/rs/hbase,60000,1572774439746
hbase_1          | 2019-11-03 09:54:20,208 WARN  [master/hbase/10.17.0.5:60000] zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=zk:2181, exception=org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /hbase/rs/hbase,60000,1572774439746
hbase_1          | 2019-11-03 09:54:25,064 WARN  [master/hbase/10.17.0.5:60000] zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=zk:2181, exception=org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /hbase/rs/hbase,60000,1572774439746
hbase_1          | 2019-11-03 09:54:30,882 WARN  [master/hbase/10.17.0.5:60000] zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=zk:2181, exception=org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /hbase/rs/hbase,60000,1572774439746
hbase_1          | 2019-11-03 09:54:39,757 WARN  [master/hbase/10.17.0.5:60000] zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=zk:2181, exception=org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /hbase/rs/hbase,60000,1572774439746
hbase_1          | 2019-11-03 09:54:39,758 ERROR [master/hbase/10.17.0.5:60000] zookeeper.RecoverableZooKeeper: ZooKeeper delete failed after 4 attempts
hbase_1          | 2019-11-03 09:54:39,760 WARN  [master/hbase/10.17.0.5:60000] regionserver.HRegionServer: Failed deleting my ephemeral node
hbase_1          | org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /hbase/rs/hbase,60000,1572774439746
hbase_1          |      at org.apache.zookeeper.KeeperException.create(KeeperException.java:127)
hbase_1          |      at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
hbase_1          |      at org.apache.zookeeper.ZooKeeper.delete(ZooKeeper.java:873)
hbase_1          |      at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.delete(RecoverableZooKeeper.java:178)
hbase_1          |      at org.apache.hadoop.hbase.zookeeper.ZKUtil.deleteNode(ZKUtil.java:1345)
hbase_1          |      at org.apache.hadoop.hbase.zookeeper.ZKUtil.deleteNode(ZKUtil.java:1334)
hbase_1          |      at org.apache.hadoop.hbase.regionserver.HRegionServer.deleteMyEphemeralNode(HRegionServer.java:1403)
hbase_1          |      at org.apache.hadoop.hbase.regionserver.HRegionServer.run(HRegionServer.java:1079)
hbase_1          |      at java.lang.Thread.run(Thread.java:748)
hbase_1          | 2019-11-03 09:54:42,580 INFO  [master/hbase/10.17.0.5:60000] regionserver.HRegionServer: stopping server hbase,60000,1572774439746; zookeeper connection closed.
hbase_1          | 2019-11-03 09:54:43,840 INFO  [master/hbase/10.17.0.5:60000] regionserver.HRegionServer: master/hbase/10.17.0.5:60000 exiting
hbase_1          | starting rest, logging to /opt/hbase-1.1.2/bin/../logs/hbase--rest-hbase.out
hadoop-docker-lite-master_hbase_1 exited with code 0

```
kafka
```
kafka_1          | [2019-11-03 09:53:39,513] INFO Session establishment complete on server zk/10.17.0.2:2181, sessionid = 0x16e30a93bf00008, negotiated timeout = 6000 (org.apache.zookeeper.ClientCnxn)
kafka_1          | [2019-11-03 09:53:39,514] INFO zookeeper state changed (SyncConnected) (org.I0Itec.zkclient.ZkClient)
kafka_1          | [2019-11-03 09:55:08,703] INFO Creating /controller (is it secure? false) (kafka.utils.ZKCheckedEphemeral)
kafka_1          | [2019-11-03 09:55:08,836] INFO Result of znode creation is: OK (kafka.utils.ZKCheckedEphemeral)
kafka_1          | [2019-11-03 09:55:08,837] INFO 0 successfully elected as leader (kafka.server.ZookeeperLeaderElector)
kafka_1          | [2019-11-03 09:55:09,210] INFO re-registering broker info in ZK for broker 0 (kafka.server.KafkaHealthcheck)
kafka_1          | [2019-11-03 09:55:09,226] INFO Creating /brokers/ids/0 (is it secure? false) (kafka.utils.ZKCheckedEphemeral)
kafka_1          | [2019-11-03 09:55:09,241] INFO Result of znode creation is: OK (kafka.utils.ZKCheckedEphemeral)
kafka_1          | [2019-11-03 09:55:09,243] INFO Registered broker 0 at path /brokers/ids/0 with addresses: PLAINTEXT -> EndPoint(192.168.99.100,9092,PLAINTEXT) (kafka.utils.ZkUtils)
kafka_1          | [2019-11-03 09:55:09,248] INFO done re-registering broker (kafka.server.KafkaHealthcheck)
kafka_1          | [2019-11-03 09:55:09,259] INFO Subscribing to /brokers/topics path to watch for new topics (kafka.server.KafkaHealthcheck)
kafka_1          | [2019-11-03 09:55:09,908] INFO New leader is 0 (kafka.server.ZookeeperLeaderElector$LeaderChangeListener)
kafka_1          | [2019-11-03 09:55:09,991] INFO re-registering broker info in ZK for broker 0 (kafka.server.KafkaHealthcheck)
kafka_1          | [2019-11-03 09:55:09,994] INFO Creating /brokers/ids/0 (is it secure? false) (kafka.utils.ZKCheckedEphemeral)
kafka_1          | [2019-11-03 09:55:10,015] INFO Result of znode creation is: OK (kafka.utils.ZKCheckedEphemeral)
kafka_1          | [2019-11-03 09:55:10,017] INFO Registered broker 0 at path /brokers/ids/0 with addresses: PLAINTEXT -> EndPoint(192.168.99.100,9092,PLAINTEXT) (kafka.utils.ZkUtils)
kafka_1          | [2019-11-03 09:55:10,017] INFO done re-registering broker (kafka.server.KafkaHealthcheck)
kafka_1          | [2019-11-03 09:55:10,018] INFO Subscribing to /brokers/topics path to watch for new topics (kafka.server.KafkaHealthcheck)
kafka_1          | [2019-11-03 09:55:10,108] INFO New leader is 0 (kafka.server.ZookeeperLeaderElector$LeaderChangeListener)
kafka_1          | /usr/bin/start-kafka.sh: line 47:    87 Killed                  $KAFKA_HOME/bin/kafka-server-start.sh $KAFKA_HOME/config/server.properties
hadoop-docker-lite-master_kafka_1 exited with code 137

```

**Comment by pkeropen** [comment]
你的搭建环境机器的配置是多少呀？

**Comment by 631068264** [comment]
4核16G
